# Generated by Django 5.2.12 on 2026-03-23 22:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="average_cost_stardust",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=24
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="stardust_balance",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("100.00000000"), max_digits=24
            ),
        ),
    ]
