# Generated by Django 5.2.12 on 2026-03-23 22:49

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models

DUST_Q = Decimal("0.00000001")


def backfill_reset_snapshot(apps, schema_editor):
    Position = apps.get_model("stocks", "Position")
    for p in Position.objects.all():
        qty = Decimal(p.quantity)
        avg = p.average_cost_stardust
        p.last_reset_value_stardust = (qty * avg).quantize(DUST_Q, rounding=ROUND_HALF_UP)
        p.save(update_fields=["last_reset_value_stardust"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_decimal_stardust"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="last_reset_value_stardust",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=24
            ),
        ),
        migrations.RunPython(backfill_reset_snapshot, noop_reverse),
    ]
