# Generated by Django 5.2.12 on 2026-03-26

from django.db import migrations


def seed_stardust_shield(apps, schema_editor):
    PowerUp = apps.get_model("stocks", "PowerUp")
    PowerUp.objects.get_or_create(
        code="STARDUST_SHIELD",
        defaults={
            "name": "Stardust Shield",
            "description": "Auto-sells a protected stock when price falls below your trigger.",
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0007_stardust_shield"),
    ]

    operations = [
        migrations.RunPython(seed_stardust_shield, noop_reverse),
    ]

