# Generated by Django 5.2.12 on 2026-03-30

from decimal import Decimal

from django.db import migrations


def grant_initial_shields(apps, schema_editor):
    Profile = apps.get_model("stocks", "Profile")
    PowerUp = apps.get_model("stocks", "PowerUp")
    UserPowerUp = apps.get_model("stocks", "UserPowerUp")

    shield_powerup, _ = PowerUp.objects.get_or_create(
        code="STARDUST_SHIELD",
        defaults={
            "name": "Stardust Shield",
            "description": "Auto-sells a protected stock when price falls below your trigger.",
        },
    )

    # Ensure every existing user has at least 1 shield to start.
    for profile in Profile.objects.all().select_related("user"):
        item, _created = UserPowerUp.objects.get_or_create(
            user=profile.user, powerup=shield_powerup, defaults={"quantity": 1}
        )
        if item.quantity < 1:
            item.quantity = 1
            item.save(update_fields=["quantity"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0008_seed_stardust_shield_powerup"),
    ]

    operations = [
        migrations.RunPython(grant_initial_shields, noop_reverse),
    ]

