# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations


def seed_multiply_profit_powerup(apps, schema_editor):
    PowerUp = apps.get_model("stocks", "PowerUp")
    PowerUp.objects.get_or_create(
        code="MULTIPLY_PROFIT_2X",
        defaults={
            "name": "Multiply Profit (2x)",
            "description": "Doubles positive profit on the next sell of the protected stock.",
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0010_multiply_profit_boost"),
    ]

    operations = [
        migrations.RunPython(seed_multiply_profit_powerup, noop_reverse),
    ]

