# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations


def grant_initial_multiply_profit_powerup(apps, schema_editor):
    Profile = apps.get_model("stocks", "Profile")
    PowerUp = apps.get_model("stocks", "PowerUp")
    UserPowerUp = apps.get_model("stocks", "UserPowerUp")

    multiply_powerup, _ = PowerUp.objects.get_or_create(
        code="MULTIPLY_PROFIT_2X",
        defaults={
            "name": "Multiply Profit (2x)",
            "description": "Doubles positive profit on the next sell of the protected stock.",
        },
    )

    for profile in Profile.objects.all().select_related("user"):
        item, created = UserPowerUp.objects.get_or_create(
            user=profile.user,
            powerup=multiply_powerup,
            defaults={"quantity": 1},
        )
        if not created and int(item.quantity or 0) < 1:
            item.quantity = 1
            item.save(update_fields=["quantity"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0011_seed_multiply_profit_powerup"),
    ]

    operations = [
        migrations.RunPython(grant_initial_multiply_profit_powerup, noop_reverse),
    ]

