# Generated by Django 4.2.7 on 2026-03-31 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0012_grant_initial_multiply_profit_powerup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("players", models.JSONField(default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recon_snapshot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
